[package]
name = "axiom_tide"
edition = "2024.beta"
# v10: upgrade from v9 (Stream package, 2026-05-13)
# v9 → 0x7bc8f81b03cede714045a9f24e5f776fc449000c9414e33908ebe177d3b5ac2b
published-at = "0x7bc8f81b03cede714045a9f24e5f776fc449000c9414e33908ebe177d3b5ac2b"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet", override = true }
usdc = { git = "https://github.com/circlefin/stablecoin-sui.git", subdir = "packages/usdc", rev = "master" }

[addresses]
axiom_tide = "0x0"
