name = "conk-zkproxy-v2"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "49eacdb17d3716275f23b560bf6cc04a"

[[kv_namespaces]]
binding = "RATE_LIMITER"
id = "bf2beb08fa7f4d85a669b2ee4f13619f"
